bot:
  token: ${TELEGRAM_TOKEN:7695093813:AAGmv9PWlvdHCeqqw9infgP5Ahs12oC7mcw}
  sheet-id: ${GOOGLE_SHEET_ID:1Nztl3OuSkJuKZr0PNE19XEeefpIh-oGaGUcAeDTzOrU}
  sheet-name: ${GOOGLE_SHEET_NAME:Лист1}
  credentials: ${GOOGLE_CREDENTIALS:/config/google.json}